server:
  port: 8000

eureka:
  server:
    enable-self-preservation: false

    instance:
      hostname: eureka-server
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      default-zone: http://localhost:8000/eureka
